import { ResetForm } from "@/components/auth/reset-form"
import { Metadata } from 'next'
export const metadata: Metadata = {
  title: 'Store - Reset Password',
  description: 'Generated by create next app',
}
const ResetPage=()=> {
    return (
      <ResetForm></ResetForm>
    )
}
export default ResetPage