import { RegisterForm } from '@/components/auth/register-form'
import React from 'react'


import { Metadata } from 'next'
export const metadata: Metadata = {
  title: 'Store - Register',
  description: 'Generated by create next app',
}
function RegisterPage() {
  return (
<RegisterForm/>
  )
}

export default RegisterPage