import { redirect } from 'next/navigation';
import {db} from '@/lib/db';
import { auth } from '@/auth';
import { ModalProvider } from '@/providers/modal-provider';
import { Metadata } from 'next';
import DashboardNavbar from '../_dashboard-components/dashboard-nav';
// import { StoreSwitcher } from '@/components/store-switcher';
export const metadata: Metadata = {
  title: 'Admin DashBoard',
  description: 'Generated by create next app',
}
export default async function DashboardLayout({
  children,
  params
}: {
  children: React.ReactNode
  params: { storeId: string }
}) {
  const  userId  = await auth();
  if (!userId) {
    redirect('/');
  }
  // const categories = getCategories()
  // console.log(categories)

  const store = await db.store.findFirst({ 
    where: {
      id: params.storeId,
      userId:userId.user.id
      }
   });
  //  const storeModal = useStoreModal();
  //  if(store){
     
  //   storeModal.onClose()
  //  }

   if (!store){
    redirect("/")}

 
  return (
    <>

          <DashboardNavbar/>

      {/* <StoreSwitcher items={[]}></StoreSwitcher> */}
    {/* <ModalProvider/>  */}

      {children}
    </>
  );
};
