import { Metadata } from "next";

export const metadata: Metadata = {
    title: 'Store - Cart',
    description: 'Generated by create next app',
  }

export default function CarLayout({ children }: { children: React.ReactNode }) {
    return <>{children}</>;
}