// this is the root layout

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import  {SessionProvider} from "next-auth/react"
import {auth} from "@/auth"
import { Toaster } from '@/components/ui/sonner'
import TheMainNavbar from '@/components/categoriesLinks'
import Billboard from '@/components/ui/billboard'
import { ToastProvider } from '@/providers/toaster-provider'
import { ThemeProvider } from '@/providers/theme-provider'
import { ModalProvider } from '@/providers/modal-provider'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Store - Next.js',
  description: 'Generated by create next app',
}


export default  async function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
 const session  = await auth()
  return (
    <SessionProvider session={session}>
    <html lang="en">
      <body className={inter.className}>
        <ModalProvider/>
      {/* <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          > */}
            {/* <div className="fixed inset-0 z-50 "> */}
            <TheMainNavbar></TheMainNavbar>

            {/* </div> */}
     <ToastProvider></ToastProvider>
        {children}
        {/* </ThemeProvider> */}
       
        </body>

    </html>

    </SessionProvider>

  )
}
