// this is the root layout


import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import  {SessionProvider} from "next-auth/react"
import {auth} from "@/auth"
import { Toaster } from '@/components/ui/sonner'
import TheMainNavbar from '@/components/categoriesLinks'
import Billboard from '@/components/ui/billboard'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
 const session  = await auth()
  return (
    <SessionProvider session={session}>
    <html lang="en">
      <body className={inter.className}>
<TheMainNavbar></TheMainNavbar>
        <Toaster></Toaster>
        {children}</body>
    </html>
    </SessionProvider>

  )
}
