import { LoginForm } from '@/components/auth/Login-form'
import React from 'react'

import { Metadata } from 'next'
export const metadata: Metadata = {
  title: 'Store - Login',
  description: 'Generated by create next app',
}
function LoginPage() {
  return (
<LoginForm/>
  )
}

export default LoginPage