import { auth } from "@/auth";
import { Button } from "@/components/ui/button";
import { db } from "@/lib/db";
import { ModalProvider } from "@/providers/modal-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import { ToastProvider } from "@/providers/toaster-provider";
import { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";


export const metadata: Metadata = {
    title: 'Admin Dashboard',
    description: 'Generated by create next app',
  }

export default async function SetupLayout({
    children
}: {
    children: React.ReactNode
}) {
    const userId  = await auth();

    if(userId?.user.role !== "ADMIN"){
        redirect('/')
    }
    const store = await db.store.findMany({
        where:{
            userId:userId.user.id
        }
    })
 
// if(store){
//     redirect(`/dashboard/${store.id}/categories`) 
// }


    return (
        <> 

 
        {/* <ToastProvider></ToastProvider> */}
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >


        </ThemeProvider>
        {children}

         </>


    )
}