import { ErrorCard } from '@/components/auth/error-card'
import React from 'react'
import { Metadata } from 'next'
export const metadata: Metadata = {
  title: 'Store - Error',
  description: 'Generated by create next app',
}
function AuthErrorPage() {
  return (
  
  <ErrorCard/>
  )
}

export default AuthErrorPage